TrabajoPracticoKinexo/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabajoPracticoKinexo.Models;
using Blog.Contract;

namespace TrabajoPracticoKinexo.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CategoriasController : Controller
    {
        private readonly ICategorias CategoriasServicios;

        public CategoriasController(ICategorias categorias)
        {
            this.CategoriasServicios = categorias;
        }

        public ActionResult Index()
        {
            List<CategoriaModel> listaCategorias = CategoriasServicios.RetornarCategorias()
                                                    .Select(x => new CategoriaModel
                                                    { Id = x.Id, Nombre = x.Nombre, Descripcion = x.Descripcion }).ToList();
            return View(listaCategorias);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriaModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Categoria categ = new Categoria { Id = model.Id, Descripcion = model.Descripcion, Nombre = model.Nombre };
            this.CategoriasServicios.CrearCategoria(categ);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int id)
        {
            Categoria categ = CategoriasServicios.RetornarCategorias().SingleOrDefault(x => x.Id == id);
            CategoriaModel categoria = new CategoriaModel { Id = categ.Id, Nombre = categ.Nombre, Descripcion = categ.Descripcion };

            return View(categoria);
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriaModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Categoria categoria = new Categoria { Id = model.Id, Nombre = model.Nombre, Descripcion = model.Descripcion };
            this.CategoriasServicios.EditarCategoria(categoria);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public JsonResult EliminarCategoria(int id)
        {
            Categoria Categoria = this.CategoriasServicios.RetornarCategoriaId(id);
            this.CategoriasServicios.EliminarCategoria(Categoria);

            return Json(new { ok = "La categoria fue eliminada con exito" }, JsonRequestBehavior.AllowGet);
        }


    }
}

TrabajoPracticoKinexo/Views/Categorias/Create.cshtml
@using TrabajoPracticoKinexo.Models
@model CategoriaModel

<h2>Crear nueva categoria</h2>

@using (Html.BeginForm("Create", "Categorias", FormMethod.Post,
                                            new { @class = "", role = "form" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary()
    @Html.Partial("_Form", Model)
}

TrabajoPracticoKinexo/Views/Categorias/Edit.cshtml
@using TrabajoPracticoKinexo.Models
@model CategoriaModel

<h1>Editar categoria</h1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary()
    @Html.HiddenFor(x => x.Id)
    @Html.Partial("_Form", Model)
}

TrabajoPracticoKinexo/Views/Categorias/Index.cshtml
@using TrabajoPracticoKinexo.Models
@model IList<CategoriaModel>

<h2>Categorias</h2>

<script>$("#grid-basic").bootgrid();</script>
@Html.ActionLink("Crear", "Create")

<table id="grid-basic" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Titulo</th>
            <th>Categoria</th>
        </tr>
        @foreach (var categoria in Model)
        {
        <tr>
            <td>@categoria.Id</td>
            <td>@categoria.Nombre</td>
            <td>@categoria.Descripcion</td>
            <td>@Html.ActionLink("Editar", "Edit", new { id = categoria.Id })</td>
            <td><a class="btnEliminar" data-id="@categoria.Id">Eliminar</a></td>
        </tr>
        }
    </thead>
</table>

@section scripts{
    <script>

        $(".btnEliminar").click(function(){
            var mensaje;
            var opcion = confirm("Esta seguro?");
            if (opcion == true) {

                var id = $(this).attr("data-id")
                $.post('@Url.Action("EliminarCategoria")/' + id, function (ok) {
                    alert(ok.ok)
                    location.reload();
                })
            }
        })

    </script>
}

TrabajoPracticoKinexo/Views/Categorias/_Form.cshtml
@using TrabajoPracticoKinexo.Models
@model CategoriaModel


<div class="form-group">
    @Html.LabelFor(x => x.Nombre)
    @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Nombre, "", new { @class = "text-danger" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Descripcion)
    @Html.TextBoxFor(x => x.Descripcion, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Descripcion)
</div>

<button type="submit">Terminado!</button>