TrabajoPracticoKinexo/Controllers/NotasController.cs
using Blog.Contract;
using Blog.Contract.Notas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using TrabajoPracticoKinexo.Models;
using Blog.Contract.Comentarios;

namespace TrabajoPracticoKinexo.Controllers
{
    public class NotasController : Controller
    {
        private readonly INotas NotasServicios;
        private readonly ICategorias CategoriasServicios;
        private readonly IComentarios ComentariosServicios;

        public NotasController(INotas serviciosNotas, ICategorias ServiciosCategorias, IComentarios comentarios)
        {
            this.NotasServicios = serviciosNotas;
            this.CategoriasServicios = ServiciosCategorias;
            this.ComentariosServicios = comentarios;
        }

        public ActionResult Index(int page = 1, int pageSize = 4)
        {
            IList<Nota> listaNotas = NotasServicios.RetornarNotas();
            NotaCategoriaModel notasCategorias = new NotaCategoriaModel();
            notasCategorias.PaginaNotas = new PagedList<Nota>(listaNotas, page, pageSize);
            notasCategorias.Categorias = this.CategoriasServicios.RetornarCategorias();

            return View(notasCategorias);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            ViewBag.Categoria = new SelectList(CategoriasServicios.RetornarCategorias().ToList(),
                                                nameof(Categoria.Id), nameof(Categoria.Nombre));
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NotaModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categoria = new SelectList(CategoriasServicios.RetornarCategorias().ToList(),
                                    nameof(Categoria.Id), nameof(Categoria.Nombre));
                return View(model);
            }

            Nota nota = new Nota { Titulo = model.Titulo, Subtitulo = model.Subtitulo,
                                   Cuerpo = Server.HtmlEncode(model.Cuerpo), Categoria = model.Categoria, NombreCategoria = this.CategoriasServicios.RetornarCategoriaId(model.Categoria).Nombre};

            this.NotasServicios.CrearNota(nota);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int id)
        {   
            var nota = NotasServicios.RetornarNotas().SingleOrDefault(x => x.Id == id);
            NotaModel notaModel = new NotaModel { Titulo = nota.Titulo, Subtitulo = nota.Subtitulo,
                                                Categoria = nota.Categoria, Cuerpo = nota.Cuerpo,
                                                NombreCategoria = nota.NombreCategoria};

            ViewBag.Categoria = new SelectList(CategoriasServicios.RetornarCategorias().ToList(),
                                                nameof(Categoria.Id), nameof(Categoria.Nombre));

            return View(notaModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Nota model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categoria = new SelectList(CategoriasServicios.RetornarCategorias().ToList(),
                                    nameof(Categoria.Id), nameof(Categoria.Nombre), model.Categoria);                
                return View(model);
            }

            Nota nota = new Nota { Titulo = model.Titulo, Subtitulo = model.Subtitulo, Cuerpo = model.Cuerpo, Categoria = model.Categoria, Id = model.Id,
                                    Activa = true, NombreCategoria = this.CategoriasServicios.RetornarCategoriaId(model.Categoria).Nombre };
            this.NotasServicios.EditarNota(nota);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult VerNota(int id)
        {
            var nota = this.NotasServicios.RetornarNotaId(id);
            NotaModel Nota = new NotaModel
            {
                Titulo = nota.Titulo,
                Categoria = nota.Categoria,
                Cuerpo = nota.Cuerpo,
                Subtitulo = nota.Subtitulo,
                Id = id,
                NombreCategoria = nota.NombreCategoria
            };

            Nota.Comentarios = new List<Comentario>();
            Nota.Comentarios.AddRange(this.ComentariosServicios.RetornarComentarios(id));

            return View(Nota);
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public JsonResult EliminarComentario(int id)
        {
            this.ComentariosServicios.EliminarComentario(id);

            return Json(new { ok = "El comentario fue eliminado" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public JsonResult EliminarNota(int id)
        {
            this.NotasServicios.EliminarNota(id);

            return Json(new { ok = "La nota fue eliminada" }, JsonRequestBehavior.AllowGet);
        }


    }
}

TrabajoPracticoKinexo/Views/Notas/Create.cshtml
@using TrabajoPracticoKinexo.Models
@model NotaModel


<h2>Crear nueva nota</h2>

@using (Html.BeginForm("Create", "Notas", FormMethod.Post,
                                new { @class = "", role = "form" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary()

    @Html.Partial("_Form", Model)    
}

TrabajoPracticoKinexo/Views/Notas/Edit.cshtml
@using TrabajoPracticoKinexo.Models
@model NotaModel

<h1>Editar nota</h1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary()
    @Html.HiddenFor(x => x.Id)
    @Html.Partial("_Form", Model)
}

TrabajoPracticoKinexo/Views/Notas/Index.cshtml
@using TrabajoPracticoKinexo.Models
@using Blog.Contract;
@using PagedList
@using PagedList.Mvc;
@model NotaCategoriaModel


<h2>Notas</h2>

<select id="selectCategory">
    <option value="">todo</option>
    @foreach (var categoria in Model.Categorias)
    {
        <option value="@categoria.Nombre">@categoria.Nombre</option>
    }

</select>

<script>$("#grid-basic").bootgrid();</script>

<style>
    a {
        color: black;
    }

        a:hover {
            color: black;
        }

        a:active {
            color: black;
        }
</style>
@Html.ActionLink("Crear", "Create")
<table id="grid-basic" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Titulo</th>
            <th>Categoria</th>
            <th>Me gusta</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Nota in Model.PaginaNotas)
        {
            <tr class="@Nota.NombreCategoria">
                <td>Id</td>
                <td>@Nota.Titulo</td>
                <td>@Nota.NombreCategoria</td>
                <td>@Nota.MeGusta</td>
                <td>@Html.ActionLink("Ver", "VerNota", new { id = Nota.Id })</td>
                <td>@Html.ActionLink("Editar", "Edit", new { id = Nota.Id })</td>
                <td><a class="btnEliminar" data-id="@Nota.Id">Eliminar</a></td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(Model.PaginaNotas, page => Url.Action("Index", new { page, pageSize = Model.PaginaNotas.PageSize }))
Showing @Model.PaginaNotas.FirstItemOnPage to @Model.PaginaNotas.LastItemOnPage of @Model.PaginaNotas.TotalItemCount Nota

@section scripts{

    <script>
        $(function () {

            var $tabla = $('#grid-basic');

            $('#selectCategory').change(function () {
                var value = $(this).val();
                if (value) {
                    $('tbody tr.' + value, $tabla).show();
                    $('tbody tr:not(.' + value + ')', $tabla).hide();
                }
                else {
                    // Se ha seleccionado All
                    $('tbody tr', $tabla).show();
                }
            });
        });
        //$('grid-basic').ddTableFilter();
    </script>


    <script>

        $(".btnEliminar").click(function(){
            var mensaje;
            var opcion = confirm("Esta seguro?");
            if (opcion == true) {

                var id = $(this).attr("data-id")
                $.post('@Url.Action("EliminarNota")/' + id, function (ok) {
                    alert(ok.ok)
                    location.reload();
                })
            }
        })

    </script>

}

TrabajoPracticoKinexo/Views/Notas/VerNota.cshtml
@using TrabajoPracticoKinexo.Models;
@model NotaModel

<h3>@Model.Titulo</h3>
<h4>@Model.Subtitulo</h4>


<div class="col-sm-12 col-sm-offset-0 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <p1>@Html.Raw(Model.Cuerpo)</p1>
    </div>
</div>

<table id="grid-basic" class="table table-condensed table-hover table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <th>Usuario</th>
            <th>Comentario</th>
            <th>Eliminar</th>
        </tr>
        @foreach (var comentario in Model.Comentarios)
        {
            <tr id=" @comentario.Id">
                <td>@comentario.Id</td>
                <td>@comentario.NombreUsuario</td>
                <td>@comentario.Texto</td>
                <td><a class="btnEliminar" data-id="@comentario.Id">Eliminar</a></td>                
            </tr>
        }
    </thead>
</table>

@section scripts{
    <script>

        $(".btnEliminar").click(function(){
            var mensaje;
            var opcion = confirm("Esta seguro?");
            if (opcion == true) {

                var id = $(this).attr("data-id")
                $.post('@Url.Action("EliminarComentario")/' + id, function (ok) {
                    alert(ok.ok)
                    location.reload();
                })
            }
        })

    </script>

    <script>

    actualizar();

    function actualizar() {
            var url = '/Notas/DevolverMeGusta';
        $.getJSON(url, { IdNota: @Model.Id }, function (resultado) {
            $("#btnMeGusta").val(resultado.cantidad + " Me gusta");
        })
    }
    </script>
}

TrabajoPracticoKinexo/Views/Notas/_Form.cshtml
@using TrabajoPracticoKinexo.Models
@model NotaModel

@*
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
*@
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>tinymce.init({ selector: 'textarea' });</script>


<div class="form-group">
    @Html.LabelFor(x => x.Titulo)
    @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Titulo, "", new { @class = "text-danger" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Subtitulo)
    @Html.TextBoxFor(x => x.Subtitulo, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Subtitulo)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Categoria)
    @Html.DropDownListFor(x => x.Categoria, (SelectList)ViewBag.Categoria, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Categoria)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Cuerpo)
    @Html.TextAreaFor(x => x.Cuerpo, new { @class = "form-control"})
    @Html.ValidationMessageFor(x => x.Cuerpo)
</div>


<button type="submit">Terminado</button>